let S=JSON.parse(localStorage.getItem('fox_unit3_review_preview_v1')||'{"xp":0,"correct":0,"wrong":0,"learned":{},"preview":false,"answered":{},"weak":{}}');
function $(id){return document.getElementById(id)}function save(){localStorage.setItem('fox_unit3_review_preview_v1',JSON.stringify(S))}function shuffle(a){return[...a].sort(()=>Math.random()-.5)}function toast(m){let t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1300)}function speak(text){let u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.85;speechSynthesis.speak(u)}function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');window.scrollTo(0,0);updateDashboard()}function updateStats(){$('xp').textContent=S.xp;$('correct').textContent=S.correct;$('wrong').textContent=S.wrong;$('learnedCount').textContent=Object.keys(S.learned).length;save()}function updateDashboard(){$('dXp').textContent=S.xp;$('dAccuracy').textContent=`答對 ${S.correct}｜答錯 ${S.wrong}`;$('dLearned').textContent=`已看過 ${Object.keys(S.learned).length} 張學習卡`;$('dPreview').textContent=S.preview?'今天已完成預習 ✅':'尚未完成預習';const weak=Object.entries(S.weak).sort((a,b)=>b[1]-a[1]).slice(0,6).map(x=>`${x[0]}：${x[1]}次`).join('、');$('dWeak').textContent=weak||'目前沒有明顯弱點';$('dSuggest').textContent=weak?'建議先重玩 Mixed Review 和 Boss。':'可以進入預習或 Discovery。';updateStats()}
function renderLearn(){$('learnCards').innerHTML=LEARN_CARDS.map(c=>`<div class="learnCard"><div class="emoji">${c.emoji}</div><div class="en">${c.en}</div><p class="zh">${c.zh}<br>${c.sentence}<br><b>${c.type}</b></p><button onclick='speak(${JSON.stringify(c.en)})'>🔊 單字</button><button onclick='speak(${JSON.stringify(c.sentence)})'>🔊 句子</button><button onclick="markLearned('${c.id}')">${S.learned[c.id]?'已看過 ✅':'我看過了'}</button></div>`).join('')}
function markLearned(id){if(!S.learned[id]){S.learned[id]=1;S.xp+=3;toast('+3 XP')}renderLearn();updateStats()}
function renderPreview(){$('previewCards').innerHTML=PREVIEW_CARDS.map(c=>`<div class="learnCard"><div class="emoji">${c.emoji}</div><div class="en">${c.en}</div><p class="zh">${c.zh}<br>${c.sentence}</p><button onclick='speak(${JSON.stringify(c.en)})'>🔊 單字</button><button onclick='speak(${JSON.stringify(c.sentence)})'>🔊 句子</button></div>`).join('')}function markPreviewDone(){if(!S.preview){S.preview=true;S.xp+=10;toast('預習完成 +10 XP')}updateDashboard()}
function renderDiscovery(){$('discoveryCards').innerHTML=DISCOVERY_CARDS.map(c=>`<div class="miniCard"><div class="emoji">${c.emoji}</div><div class="en">${c.en}</div><p class="zh">${c.zh}<br>${c.sentence}</p><button onclick='speak(${JSON.stringify(c.sentence)})'>🔊</button></div>`).join('')}
function norm(q){return {q:q[0],ans:q[1],choices:q[2],hint:q[3]}}function makeQuestion(raw,keyPrefix,i){let q=norm(raw);const key=keyPrefix+'_'+i+'_'+q.q.slice(0,12);const choices=shuffle(q.choices);return `<div class="q" data-attempts="1"><h3>${q.q}</h3>${choices.map(c=>`<button class="choice" onclick='answer(this,${JSON.stringify(c)},${JSON.stringify(q.ans)},${JSON.stringify(key)},${JSON.stringify(q.q)})'>${c}</button>`).join('')}<div class="hint hidden">💡 ${q.hint}</div></div>`}
function answer(btn,choice,ans,key,label){const box=btn.parentElement;if(btn.disabled)return;if(choice===ans){btn.classList.add('correct');box.querySelectorAll('button').forEach(b=>b.disabled=true);if(!S.answered[key]){S.answered[key]=1;S.correct++;S.xp+=10}toast('Correct +10 XP')}else{btn.classList.add('wrongBtn');btn.disabled=true;S.wrong++;S.weak[label]=(S.weak[label]||0)+1;let n=Number(box.dataset.attempts||1)+1;box.dataset.attempts=n;if(n>=3)box.querySelector('.hint').classList.remove('hidden');toast('錯的選項已鎖住')}updateDashboard();checkBossDone()}
function renderReview(type='mixed'){let pool=[];if(type==='food')pool=FOOD_QUESTIONS;if(type==='grammar')pool=GRAMMAR_QUESTIONS;if(type==='reading')pool=READING_QUESTIONS;if(type==='animals')pool=ANIMAL_QUESTIONS;if(type==='mixed')pool=[...FOOD_QUESTIONS,...GRAMMAR_QUESTIONS,...READING_QUESTIONS,...ANIMAL_QUESTIONS];$('reviewBox').innerHTML=shuffle(pool).slice(0,type==='mixed'?30:18).map((q,i)=>makeQuestion(q,type,i)).join('')}
function renderBoss(){const pool=[...ANIMAL_QUESTIONS,...FOOD_QUESTIONS,...GRAMMAR_QUESTIONS,...READING_QUESTIONS];$('bossBox').innerHTML=shuffle(pool).slice(0,20).map((q,i)=>makeQuestion(q,'boss',i)).join('')}function checkBossDone(){const total=document.querySelectorAll('#bossBox .q').length;const done=document.querySelectorAll('#bossBox .q .correct').length;if(total&&done>=total)$('bossDone').classList.remove('hidden')}function resetAll(){localStorage.removeItem('fox_unit3_review_preview_v1');location.reload()}
renderLearn();renderPreview();renderDiscovery();renderReview('mixed');renderBoss();updateDashboard();