
const STORE='fox_academy_v101';
let S=JSON.parse(localStorage.getItem(STORE)||'{"xp":0,"coins":0,"correct":0,"claimed":{},"wrong":{},"stars":{},"review":{},"reviewed":{},"login":{},"done":{},"cards":{},"owned":{}}');
let hp=210; const today=new Date().toDateString();
const school=[['🍎 Apple','Fruits','Apple is a fruit.'],['🍌 Banana','Fruits','Bananas are yellow fruits.'],['🥛 Milk','Dairy','Milk is dairy.'],['🧀 Cheese','Dairy','Cheese is dairy.'],['🍚 Rice','Grains','Rice is a grain.'],['🍞 Bread','Grains','Bread is made from grain.'],['🥚 Egg','Protein','Egg is protein.'],['🐟 Fish','Protein','Fish is protein.'],['🥕 Carrot','Vegetables','Carrot is a vegetable.'],['🥬 Spinach','Vegetables','Spinach is leafy vegetable.']];
const extended=[['🥝 Kiwi','Fruits','Kiwi is green inside.'],['🍇 Grape','Fruits','Grapes grow in bunches.'],['🍑 Peach','Fruits','Peach is a sweet fruit.'],['🍐 Pear','Fruits','Pear is a fruit.'],['🫘 Beans','Protein','Beans are protein food.'],['🥣 Cereal','Grains','Cereal is a grain product.']];
const life=[['🛒 Supermarket','Place','We buy fruit at the supermarket.'],['🌱 Seed','Nature','Apples have seeds.'],['☀️ Warm','Adjective','Bananas grow in warm places.'],['💪 Calcium','Nutrition','Milk has calcium.']];
const animals=[['🦁 a group of lions',['pride','pack','school'],'pride','Lions live in a pride.'],['🐺 a group of wolves',['pack','flock','bed'],'pack','Wolves are a pack.'],['🐟 a group of fish',['school','pod','army'],'school','Fish swim in a school.'],['🐬 a group of dolphins',['pod','herd','tower'],'pod','Dolphins are a pod.'],['🐝 a group of bees',['swarm','clowder','parade'],'swarm','Bees fly in a swarm.'],['animals with backbones',['vertebrates','invertebrates','mollusks'],'vertebrates','Backbone means vertebrate.']];
const grammar=[['Whole fruit is ______ than fruit juice.',['healthier','healthy','healthiest'],'healthier','Use -er to compare.'],['I ______ going to eat fruit.',['am','is','are'],'am','I am.'],['She ______ going to exercise.',['am','is','are'],'is','She is.'],['good 的比較級是？',['better','gooder','best'],'better','good is irregular: better.']];
const allCards=[...school.map(x=>['Food',...x]),...extended.map(x=>['Discovery',...x]),...life.map(x=>['Life',...x]),...animals.map(x=>['Animal',x[0],x[2],x[3]])];
function save(){localStorage.setItem(STORE,JSON.stringify(S))}
function go(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo(0,0);if(id==='collection')renderCollection();if(id==='review')renderReview();if(id==='homeFox')renderHome();update()}
function toast(m){let t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1500)}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function speak(txt){let u=new SpeechSynthesisUtterance(txt);u.lang='en-US';u.rate=.86;speechSynthesis.speak(u)}
function confetti(){const layer=document.getElementById('fxLayer');layer.innerHTML='';for(let i=0;i<80;i++){let s=document.createElement('span');s.className='confetti';s.textContent=['🎉','⭐','🦊','💰','✨','🎴'][Math.floor(Math.random()*6)];s.style.left=Math.random()*100+'%';s.style.top='-40px';s.style.animationDelay=Math.random()*.6+'s';layer.appendChild(s)}setTimeout(()=>layer.innerHTML='',3200)}
function stars(n){return Math.max(1,4-n)} function starText(n){return '⭐'.repeat(n)+'☆'.repeat(3-n)}
function collect(label){S.cards[label]=1;save();update();toast('收藏：'+label)}
function markWrong(k,l){S.wrong[k]=(S.wrong[k]||0)+1;S.review[k]=l;save();update()}
function award(k,xp,att=1,label=''){if(S.claimed[k]){toast('已完成過 ✅');return false}let st=stars(att);S.claimed[k]=1;S.stars[k]=st;S.xp+=xp*st;S.coins+=st+Math.floor(xp/3);S.correct++;if(label)collect(label);save();update();toast(starText(st)+' +'+(xp*st)+' XP');return true}
function answer(btn,a,ans,k,l,hid,xp){let n=Number(btn.parentElement.dataset.attempts||1);if(btn.disabled)return;if(a===ans){btn.classList.add('correct');award(k,xp,n,l);btn.parentElement.querySelectorAll('button').forEach(b=>b.disabled=true)}else{btn.classList.add('wrong','locked');btn.disabled=true;markWrong(k,l);n++;btn.parentElement.dataset.attempts=n;if(n>=3&&hid)document.getElementById(hid).classList.remove('hidden');toast('錯的選項已鎖住')}}
function makeQuiz(items,prefix,xp){return shuffle(items).map((q,i)=>`<div class="quest"><h3>${q[0]}</h3><div class="hint hidden" id="${prefix}_h_${i}">💡 Hint: ${q[3]}</div>${shuffle(q[1]).map(a=>`<button class="choice" onclick="answer(this,'${a}','${q[2]}','${prefix}_${i}_${q[0].replace(/\W/g,'')}','${q[0]}','${prefix}_h_${i}',${xp})">${a}</button>`).join('')}</div>`).join('')}
function claimLogin(){if(S.login.last===today){toast('今天已打卡 ✅');return}let y=new Date(Date.now()-86400000).toDateString();S.login.streak=(S.login.last===y)?(S.login.streak||0)+1:1;S.login.last=today;let reward=20+S.login.streak*5;S.coins+=reward;S.xp+=10;save();renderDaily();update();confetti();toast(`Day ${S.login.streak} +${reward} coins`)}
function renderDaily(){let st=S.login.streak||0;document.getElementById('dailyStatus').innerHTML=`目前連續登入：🔥 ${st} 天<br>${S.login.last===today?'今天已打卡 ✅':'今天尚未打卡'}`;document.getElementById('streakRewards').innerHTML=[1,2,3,7,14,30].map(d=>`<div class="mini">${st>=d?'✅':'🎁'}<b>Day ${d}</b><small>${d===7?'Rare Fox Hat':d===30?'Legend Fox':'Coins Bonus'}</small></div>`).join('')}
function renderQuest(){let tasks=[['Vocabulary','完成核心單字','playWorld("Supermarket")'],['Reading','完成閱讀題','playReading()'],['Grammar','完成文法題','playGrammar()'],['Animal Note','老師補充','playAnimals()'],['Boss','打 Boss','go("boss")']];document.getElementById('questList').innerHTML=tasks.map((t,i)=>`<div class="mission"><h3>${i+1}. ${t[0]}</h3><p>${t[1]}</p><button onclick='${t[2]}'>開始</button><button onclick="completeQuest(${i})">標記完成</button></div>`).join('')}
function completeQuest(i){S.done['quest_'+today+'_'+i]=1;save();update();toast('任務完成 ✅');let c=[0,1,2,3,4].filter(x=>S.done['quest_'+today+'_'+x]).length;if(c>=5&&!S.done['chest_'+today]){S.done['chest_'+today]=1;S.coins+=100;S.xp+=60;document.getElementById('chestBox').classList.remove('hidden');document.getElementById('chestBox').innerHTML='🎁 Daily Chest Open!<br>+100 Coins +60 XP<br>🦊 Fox Badge';confetti();save();update()}}
function renderWorld(){let w=[['🛒','Supermarket','Food + 水果延伸','Supermarket'],['🌳','Forest','生活英文與探索','Forest'],['🦁','Zoo','Animal groups','Zoo'],['🏫','School','Grammar','School'],['👾','Boss Tower','混合挑戰','Boss']];document.getElementById('worldBox').innerHTML=w.map(x=>`<div class="world"><div class="cardEmoji">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p><button onclick="playWorld('${x[3]}')">進入</button></div>`).join('')}
function playWorld(type){document.getElementById('playCard').classList.remove('hidden');document.getElementById('playTitle').textContent=type;let data=[];if(type==='Supermarket')data=[...school,...extended].map(x=>[x[0],['Fruits','Vegetables','Grains','Protein','Dairy'],x[1],x[2]]);else if(type==='Forest')data=life.map(x=>[x[0],['Place','Nature','Adjective','Nutrition'],x[1],x[2]]);else if(type==='Zoo'){playAnimals();return}else if(type==='School'){playGrammar();return}else{go('boss');return}document.getElementById('playBox').innerHTML=makeQuiz(data,'world_'+type,6);go('world')}
function playReading(){let r=[['Who is Eva?',['little sister','teacher','doctor'],'little sister','Eva is family.'],['Which is healthier?',['whole fruit','fruit juice','candy'],'whole fruit','Whole fruit is healthier.'],['Which grains are better?',['whole grains','refined grains','no grains'],'whole grains','Better means healthier.']];document.getElementById('playCard').classList.remove('hidden');document.getElementById('playTitle').textContent='Reading Adventure';document.getElementById('playBox').innerHTML=makeQuiz(r,'reading',7);go('world')}
function playGrammar(){document.getElementById('playCard').classList.remove('hidden');document.getElementById('playTitle').textContent='Grammar School';document.getElementById('playBox').innerHTML=makeQuiz(grammar,'grammar',6);go('world')}
function playAnimals(){document.getElementById('playCard').classList.remove('hidden');document.getElementById('playTitle').textContent='Animal Zoo';document.getElementById('playBox').innerHTML=makeQuiz(animals,'animal',6);go('world')}
let currentCat='All';function setCat(c){currentCat=c;renderCollection()}
function renderCollection(){let cats=['All','Food','Discovery','Life','Animal'];document.getElementById('collectionTabs').innerHTML=cats.map(c=>`<button onclick="setCat('${c}')">${c}</button>`).join('');let list=currentCat==='All'?allCards:allCards.filter(c=>c[0]===currentCat);let owned=list.filter(c=>S.cards[c[1]]).length;document.getElementById('collectionProgress').innerHTML=`${currentCat} 收藏：${owned} / ${list.length}`;document.getElementById('collectionBox').innerHTML=list.map(c=>{let ok=S.cards[c[1]];return `<div class="collect ${ok?'':'lockedCard'}"><div class="cardEmoji">${ok?c[1].split(' ')[0]:'❓'}</div><div class="en">${ok?c[1]:'未收藏'}</div><p class="zh">${ok?c[3]:'去自由冒險或答題收集。'}</p>${ok?`<button onclick="speak('${c[3]}')">🔊</button>`:''}</div>`}).join('')}
function renderReview(){let keys=Object.keys(S.review);document.getElementById('reviewBox').innerHTML=keys.length?keys.map(k=>`<div class="quest"><h3>${S.review[k]}</h3><p>錯過 ${S.wrong[k]||0} 次｜${S.reviewed[k]?'已複習 ✅':'待複習'}</p><button onclick="S.reviewed['${k}']=1;S.xp+=5;save();renderReview();update();toast('+5 XP')">我已複習</button></div>`).join(''):'<div class="win">目前沒有錯題。很棒！</div>'}
function renderBoss(){hp=210;document.getElementById('bossWin').classList.add('hidden');drawHp();let pool=[['Which food group is milk?',['Dairy','Protein','Grains'],'Dairy','Milk is dairy.'],['Which is healthier?',['whole fruit','fruit juice','fries'],'whole fruit','Whole fruit is healthier.'],['I ___ going to exercise.',['am','is','are'],'am','I am.'],['A group of lions is a ____.',['pride','pack','school'],'pride','Lions = pride.'],['Which is an extended fruit?',['kiwi','rice','milk'],'kiwi','Kiwi is a fruit.'],['Milk has ____.',['calcium','sand','paper'],'calcium','Milk has calcium.']];document.getElementById('bossBox').innerHTML=makeQuiz(pool,'boss',8)+`<button class="big" onclick="bossClear()">我完成 Boss</button>`}
function bossClear(){if(S.done['boss_'+today])toast('今天 Boss 已領過');else{S.done['boss_'+today]=1;S.coins+=120;S.xp+=60;document.getElementById('bossWin').classList.remove('hidden');document.getElementById('bossWin').innerHTML='🏆 Boss Defeated!<br>🎁 +120 Coins<br>🦊 Fox Hero Badge';confetti();save();update()}}
function drawHp(){document.getElementById('hpBox').textContent='❤️❤️❤️❤️❤️❤️❤️ '+hp}
function renderHome(){let owned=Object.keys(S.owned);document.getElementById('roomBox').innerHTML='🦊 '+(owned.length?owned.map(k=>items.find(i=>i[0]===k)?.[1]||'').join(' '):'狐狸小屋還很空，去買家具吧！');document.getElementById('shopBox').innerHTML=items.map(i=>`<div class="shop ${S.owned[i[0]]?'correct':''}"><div class="cardEmoji">${i[1].split(' ')[0]}</div><h3>${i[1]}</h3><p>${i[2]} coins</p><button onclick="buy('${i[0]}',${i[2]})">${S.owned[i[0]]?'已擁有':'購買'}</button></div>`).join('')}
const items=[['bed','🛏️ Bed',60],['plant','🪴 Plant',40],['books','📚 Bookshelf',80],['hat','🎩 Fox Hat',100],['dog','🐶 Puppy',150],['lamp','💡 Lamp',70]];
function buy(k,p){if(S.owned[k])return toast('已擁有');if(S.coins<p)return toast('Coins 不夠');S.coins-=p;S.owned[k]=1;save();renderHome();update();confetti();toast('購買成功')}
function update(){let lv=Math.floor(S.xp/300)+1;['xpA','pXp'].forEach(id=>document.getElementById(id).textContent=S.xp);['coinA','pCoins'].forEach(id=>document.getElementById(id).textContent=S.coins);document.getElementById('levelA').textContent=lv;document.getElementById('pLevel').textContent=lv;document.getElementById('streakA').textContent=S.login.streak||0;document.getElementById('pStreak').textContent=S.login.streak||0;document.getElementById('barA').style.width=Math.min(100,(S.xp%300)/3)+'%';document.getElementById('pCards').textContent=Object.keys(S.cards).length+' / '+allCards.length;let vals=Object.values(S.stars);document.getElementById('pStars').textContent=vals.length?`平均 ${(vals.reduce((a,b)=>a+b,0)/vals.length).toFixed(1)} 星｜共 ${vals.length} 題`:'尚無星星紀錄';let w=Object.entries(S.wrong).sort((a,b)=>b[1]-a[1]).slice(0,8).map(x=>`${S.review[x[0]]||x[0]}：${x[1]}次`).join('、');document.getElementById('pWrong').textContent=w||'目前沒有明顯錯題';document.getElementById('pSuggest').textContent=w?'建議先玩 Review Cave，再玩自由冒險。':'可以挑戰 Boss Tower 或收集 Discovery Cards。'}
function resetGame(){if(confirm('確定清除所有紀錄？')){localStorage.removeItem(STORE);location.reload()}}
renderDaily();renderQuest();renderWorld();renderCollection();renderBoss();renderHome();update();
